<a href="https://colab.research.google.com/github/rhRohitHalder/ml-practice/blob/main/spam_or_not_Spam_logictic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [45]:
df = pd.read_csv('/content/mail_data.csv')

In [46]:
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [47]:
#replace the null values with null string
mail_data = df.where((pd.notnull(df)),'')

In [48]:
mail_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [49]:
mail_data.describe()

       Category                 Message
count      5572                    5572
unique        2                    5157
top         ham  Sorry, I'll call later
freq       4825                      30

In [50]:
mail_data.columns

Index(['Category', 'Message'], dtype='object')

In [51]:
mail_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

In [52]:
mail_data.duplicated().sum() ## duplicate

np.int64(415)

label encoding

In [53]:
# label spam as 0 , ham as 1
mail_data.loc[mail_data['Category'] == 'spam' , 'Category', ] = 0
mail_data.loc[mail_data['Category'] == 'ham' , 'Category', ] = 1

In [54]:
mail_data.head()

  Category                                            Message
0        1  Go until jurong point, crazy.. Available only ...
1        1                      Ok lar... Joking wif u oni...
2        0  Free entry in 2 a wkly comp to win FA Cup fina...
3        1  U dun say so early hor... U c already then say...
4        1  Nah I don't think he goes to usf, he lives aro...

In [55]:
#seperating data as text and label
X = mail_data['Message']
Y = mail_data['Category']

In [56]:
#splitting data into train test data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=3)

In [57]:
print(X.shape, X_train.shape, X_test.shape)
print(Y.shape, Y_train.shape, Y_test.shape)

(5572,) (4457,) (1115,)
(5572,) (4457,) (1115,)

**Feature extraction**
from text is the process of converting unstructured text (sentences, documents, reviews, emails, etc.) into numerical features that a machine learning model can understand.

Since ML algorithms work only with numbers, text must first be transformed into vectors.

Why is it needed?

For example, consider two movie reviews:

"This movie is amazing."
"This movie is terrible."

A machine cannot understand the words "amazing" or "terrible" directly. Feature extraction converts them into numerical representations.


# **TF-IDF (Term Frequency-Inverse Document Frequency)**
This is the most commonly used feature extraction technique in classical machine learning.

Instead of simply counting words, TF-IDF gives higher importance to unique words and lower importance to very common words.

Formula
Term Frequency (TF)

Measures how often a word appears in a document.

TF=
Total number of words in the document
Number of occurrences of a word
	​

Inverse Document Frequency (IDF)

Measures how unique a word is across all documents.

IDF=log( Documents containing the word Total documents )
TF−IDF=TF×IDF

In [58]:
#transform text to feature vector / numerical values
feature_extraction = TfidfVectorizer(min_df = 1, stop_words='english', lowercase=True)
# min_df = 1 ----- Ignore words that appear in fewer than 1 document.
# stop_words='english' ----- Removes common English words..
# lowercase=True ---   Converts every word into lowercase

In [59]:
X_test_features = feature_extraction.fit_transform(X_test)
X_train_features = feature_extraction.transform(X_train)

y_train_features = Y_train.astype('int')
y_test_features = Y_test.astype('int')

In [60]:
print(X_train_features , X_test_features)
print(y_train_features , y_test_features)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 26266 stored elements and shape (4457, 3296)>
  Coords	Values
  (0, 965)	0.5004288378302826
  (0, 1011)	0.5121802363891164
  (0, 1676)	0.44180843810740683
  (0, 1973)	0.540414366701437
  (1, 393)	0.22963747698535622
  (1, 790)	0.2870087870323566
  (1, 861)	0.32804822076875084
  (1, 1173)	0.32804822076875084
  (1, 1183)	0.29700308760673033
  (1, 1281)	0.32804822076875084
  (1, 1282)	0.32804822076875084
  (1, 1327)	0.2659579544447098
  (1, 1394)	0.30988798203907403
  (1, 1469)	0.32804822076875084
  (1, 1676)	0.18387908697192132
  (1, 1795)	0.19500733823135422
  (2, 169)	0.6016135433955984
  (2, 1039)	0.5648279137945434
  (2, 1380)	0.5648279137945434
  (3, 1242)	0.5725037544983402
  (3, 3293)	0.819902098475973
  (4, 25)	0.23042934208469248
  (4, 101)	0.23042934208469248
  (4, 177)	0.2842251356671194
  (4, 188)	0.2684908746959916
  :	:
  (4453, 3132)	0.285130349761704
  (4453, 3144)	0.2340921073175086
  (4453, 3193)	0.4028316134407369
  (4454, 1375)	0.5677996572229239
  (4454, 2036)	0.45655289013088
  (4454, 2711)	0.684954748702913
  (4455, 976)	0.3929392485059096
  (4455, 1060)	0.371186743516232
  (4455, 1694)	0.2925202842632958
  (4455, 1725)	0.33400059062119924
  (4455, 1973)	0.2694095224631233
  (4455, 2085)	0.3437818282531888
  (4455, 2506)	0.32573067203868555
  (4455, 2688)	0.2533094277468112
  (4455, 3068)	0.2087117470358561
  (4455, 3157)	0.32573067203868555
  (4456, 132)	0.27701687869309055
  (4456, 1242)	0.35848448064796024
  (4456, 2463)	0.5540337573861811
  (4456, 2566)	0.1916785607406628
  (4456, 2666)	0.24705254911253058
  (4456, 2761)	0.20744185999552392
  (4456, 2786)	0.28666323822953726
  (4456, 3171)	0.4386111946870101
  (4456, 3174)	0.26913522906566 <Compressed Sparse Row sparse matrix of dtype 'float64'
	with 8754 stored elements and shape (1115, 3296)>
  Coords	Values
  (0, 3070)	0.2019133927418629
  (0, 1934)	0.17330174484963604
  (0, 15)	0.27496518403029063
  (0, 3217)	0.19247874892161249
  (0, 1)	0.24056653549202825
  (0, 582)	0.23372196647595156
  (0, 665)	0.2597435395640047
  (0, 2303)	0.19462454405004664
  (0, 4)	0.2597435395640047
  (0, 12)	0.23372196647595156
  (0, 9)	0.24894361094223744
  (0, 167)	0.22793496582991604
  (0, 461)	0.24056653549202825
  (0, 2374)	0.2229220378541843
  (0, 90)	0.27496518403029063
  (0, 446)	0.24056653549202825
  (0, 602)	0.27496518403029063
  (0, 123)	0.21454496240397508
  (1, 2090)	0.21027980031276255
  (1, 2872)	0.2646484069642073
  (1, 2746)	0.3657167812431158
  (1, 3272)	0.2646484069642073
  (1, 2980)	0.40394441808274295
  (1, 2110)	0.40394441808274295
  (1, 2908)	0.3051274103611202
  :	:
  (1111, 1048)	0.41634461146294477
  (1111, 3264)	0.52393640273841
  (1112, 2566)	0.20631025612221207
  (1112, 2780)	0.27629390258890824
  (1112, 2225)	0.24122143926545364
  (1112, 1011)	0.22145192786940623
  (1112, 3134)	0.28250702286694024
  (1112, 1833)	0.29816283559574497
  (1112, 2529)	0.28967954384408806
  (1112, 468)	0.29816283559574497
  (1112, 3005)	0.28967954384408806
  (1112, 732)	0.34079718857361213
  (1112, 2702)	0.34079718857361213
  (1112, 1067)	0.34079718857361213
  (1113, 1795)	0.2548820491114077
  (1113, 965)	0.27222559548769554
  (1113, 1676)	0.24033699911607986
  (1113, 1775)	0.28839760382645435
  (1113, 1357)	0.28330391508527664
  (1113, 1448)	0.2969798432041589
  (1113, 1567)	0.428771570727726
  (1113, 1198)	0.428771570727726
  (1113, 1230)	0.428771570727726
  (1114, 2013)	0.5227331585592283
  (1114, 1773)	0.8524963606624327
3075    1
1787    1
1614    1
4304    1
3266    0
       ..
789     0
968     1
1667    1
3321    1
1688    0
Name: Category, Length: 4457, dtype: int64 2632    0
454     1
983     0
1282    1
4610    1
       ..
4827    1
5291    1
3325    1
3561    1
1136    1
Name: Category, Length: 1115, dtype: int64

train ML model

In [61]:
model = LogisticRegression()

In [62]:
model.fit(X_train_features,y_train_features )

LogisticRegression()

evalute the training model

In [63]:
pred_on_training_data = model.predict(X_train_features)
accuracy_on_training_data = accuracy_score(y_train_features, pred_on_training_data)

In [64]:
print('Accuracy on training data : ', accuracy_on_training_data)

Accuracy on training data :  0.9757684541171191

In [65]:
pred_on_test_data = model.predict(X_test_features)
accuracy_on_test_data = accuracy_score(y_test_features, pred_on_test_data)

In [66]:
print('Accuracy on test data : ', accuracy_on_test_data)

Accuracy on test data :  0.9542600896860987